import { readFile } from "node:fs/promises";
import { NextResponse } from "next/server";

const sourceDirectory = "D:\\SuperCampus(Web)\\Super Campus student dashboard";

export const dynamic = "force-dynamic";

export async function GET() {
  const source = await readFile(`${sourceDirectory}\\Super Campus Dashboard.dc.html`, "utf8");
  const finesBreakdown = `
            <div style="width:100%;margin:0 0 16px;padding:12px 13px;background:#fff8ec;border:1px solid #ffe6bd;border-radius:11px">
              <div style="font:700 11px 'Plus Jakarta Sans';color:#6c7280;text-transform:uppercase;letter-spacing:.05em;margin-bottom:8px">Pending fees &amp; fines</div>
              <div style="display:flex;justify-content:space-between;font-size:12px;color:#3a3d4a;padding:4px 0"><span>Tuition Fee</span><b style="font:700 12px 'JetBrains Mono';color:#ef4444">&#8377;16,000</b></div>
              <div style="display:flex;justify-content:space-between;font-size:12px;color:#3a3d4a;padding:4px 0"><span>Hostel Fee</span><b style="font:700 12px 'JetBrains Mono';color:#ef4444">&#8377;18,000</b></div>
              <div style="display:flex;justify-content:space-between;font-size:12px;color:#3a3d4a;padding:4px 0"><span>Food/Mess Fee</span><b style="font:700 12px 'JetBrains Mono';color:#d97706">&#8377;6,000</b></div>
              <div style="display:flex;justify-content:space-between;font-size:12px;color:#3a3d4a;padding:4px 0"><span>Examination Fee</span><b style="font:700 12px 'JetBrains Mono';color:#d97706">&#8377;1,800</b></div>
              <div style="display:flex;justify-content:space-between;font-size:12px;color:#3a3d4a;padding:4px 0"><span>Library Fee</span><b style="font:700 12px 'JetBrains Mono';color:#d97706">&#8377;500</b></div>
              <div style="display:flex;justify-content:space-between;font-size:12px;color:#3a3d4a;padding:4px 0"><span>Miscellaneous Fee</span><b style="font:700 12px 'JetBrains Mono';color:#d97706">&#8377;1,500</b></div>
              <div style="display:flex;justify-content:space-between;font-size:12px;color:#3a3d4a;padding:4px 0"><span>Fines</span><b style="font:700 12px 'JetBrains Mono';color:#ef4444">&#8377;20</b></div>
            </div>`;
  const finesSection = `
        <div style="font:600 12px 'Plus Jakarta Sans';letter-spacing:.05em;text-transform:uppercase;color:#9096a4;margin:24px 0 12px">Fines</div>
        <div style="background:#ffffff;border:1px solid #ececf2;border-radius:14px;box-shadow:0 1px 3px rgba(30,20,80,.05);padding:8px 20px">
          <details style="border-bottom:1px solid rgba(25,20,60,.06);padding:13px 0">
            <summary style="display:flex;align-items:center;gap:12px;cursor:pointer;list-style:none;font-size:13px;font-weight:600;color:#141527">
              <span style="width:30px;height:30px;border-radius:9px;background:rgba(239,68,68,.12);display:flex;align-items:center;justify-content:center;color:#ef4444;font-size:16px">!</span>
              <span style="flex:1"><span style="display:block">Library overdue fine</span><span style="display:block;font-size:11px;color:#9096a4;font-weight:500;margin-top:3px">Microwave Engineering &middot; 4 days overdue</span></span>
              <span style="font:700 13px 'JetBrains Mono';color:#ef4444">&#8377;20</span>
              <span style="font-size:16px;color:#9096a4">&#8964;</span>
            </summary>
            <div style="margin:10px 0 2px 42px;padding:11px 13px;background:#fff8f8;border-left:3px solid #ef4444;border-radius:0 8px 8px 0;font-size:11.5px;color:#6c7280;line-height:1.55"><b style="color:#3a3d4a">Reason for fine</b><br/>The book was returned 4 days after its due date (20 Jul 2026). Library policy applies a &#8377;5 charge per overdue day. Pay this fine from the Fees payment flow.</div>
          </details>
          <div style="display:flex;align-items:center;justify-content:space-between;padding:12px 0 8px;font-size:11px;color:#9096a4"><span>1 imposed fine</span><b style="font:700 12px 'JetBrains Mono';color:#ef4444">&#8377;20 pending</b></div>
        </div>
`;
  const profileStyles = `<style>
.profile-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(272px,342px);gap:18px;align-items:stretch}.profile-main{min-width:0;display:grid;grid-template-rows:auto minmax(0,1fr);gap:18px}.profile-card{padding:20px!important}.profile-summary{min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.profile-summary__title{margin:0 0 12px!important}.profile-summary__cards{height:100%;grid-template-rows:repeat(2,minmax(0,1fr))}.profile-summary__card{height:100%;min-height:0;padding:16px!important}.student-id-card{background:#fff;border:1px solid #ececf2;border-radius:14px;box-shadow:0 1px 3px rgba(30,20,80,.05);padding:12px;min-height:0;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:10px}.student-id-card__toggle{position:absolute;opacity:0;pointer-events:none}.student-id-card__frame{min-height:0;height:100%;perspective:1100px}.student-id-card__inner{position:relative;width:100%;height:100%;transform-style:preserve-3d;transition:transform .6s ease}.student-id-card__face{position:absolute;inset:0;border-radius:10px;overflow:hidden;backface-visibility:hidden;-webkit-backface-visibility:hidden;background:#fff}.student-id-card__face--back{transform:rotateY(180deg)}.student-id-card__face img{display:block;width:100%;height:100%;object-fit:contain;object-position:center}.student-id-card__toggle:checked~.student-id-card__frame .student-id-card__inner{transform:rotateY(180deg)}.student-id-card__controls{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:30px}.student-id-card__caption{font:700 11px 'Plus Jakarta Sans';color:#9096a4;text-transform:uppercase;letter-spacing:.05em}.student-id-card__flip{display:inline-flex;align-items:center;gap:6px;border:1px solid rgba(119,108,245,.22);border-radius:8px;background:#f5f3ff;color:#776cf5;padding:6px 9px;font:700 11px 'Plus Jakarta Sans';cursor:pointer}.student-id-card__flip-back{display:none}.student-id-card__toggle:checked~.student-id-card__controls .student-id-card__flip-front{display:none}.student-id-card__toggle:checked~.student-id-card__controls .student-id-card__flip-back{display:inline}@media(max-width:900px){.profile-layout{grid-template-columns:1fr}.profile-main{display:block}.profile-summary{display:block;margin-top:18px}.profile-summary__cards{height:auto}.profile-summary__card{height:auto;min-height:104px}.student-id-card{width:100%;max-width:380px;min-height:600px;margin:0 auto}.profile-layout .student-id-card{grid-row:1}}@media(max-width:620px){.profile-card{align-items:flex-start!important;flex-wrap:wrap}.profile-card__status{margin-left:92px}.profile-summary__cards{grid-template-columns:repeat(2,minmax(0,1fr))}.student-id-card{min-height:540px}}</style>`;
  const profileLayout = `
        <div class="profile-layout">
          <div class="profile-main">
            <div class="profile-card" style="background:#ffffff;border:1px solid #ececf2;border-radius:14px;box-shadow:0 1px 3px rgba(30,20,80,.05);display:flex;align-items:center;gap:20px"><div style="width:72px;height:72px;border-radius:16px;background:linear-gradient(135deg,#1400ff,#a600ff);display:flex;align-items:center;justify-content:center;font:800 26px 'Plus Jakarta Sans';color:#fff;flex:none">{{student.initials}}</div><div style="flex:1"><div style="font:800 20px 'Plus Jakarta Sans'">{{student.name}}</div><div style="font-size:12.5px;color:#6c7280;margin-top:3px">{{student.roll}} &middot; Electronics &amp; Communication &middot; Sri Venkateswara College of Engineering</div><div style="display:flex;gap:8px;margin-top:10px"><span style="font:700 10px 'Plus Jakarta Sans';background:rgba(119,108,245,.16);color:#a600ff;padding:4px 10px;border-radius:20px">4th Year</span><span style="{{personaPill}}">{{personaLabel}}</span></div></div><span class="profile-card__status" style="font:700 11px 'Plus Jakarta Sans';color:#9096a4;background:#f5f6fa;border:1px solid rgba(25,20,60,.11);border-radius:20px;padding:8px 14px">Read-only profile</span></div>
            <div class="profile-summary"><div class="profile-summary__title" style="font:600 12px 'Plus Jakarta Sans';letter-spacing:.05em;text-transform:uppercase;color:#9096a4">360&deg; summary</div><div class="profile-summary__cards" style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px"><sc-for list="{{summaryCards}}" as="c" hint-placeholder-count="6"><button class="profile-summary__card" onClick="{{c.onClick}}" style="background:#ffffff;border:1px solid #ececf2;border-radius:13px;box-shadow:0 1px 3px rgba(30,20,80,.05);text-align:left;cursor:pointer" style-hover="border-color:#776cf5;background:#f5f6fa"><div style="font-size:11px;color:#9096a4;font-weight:600;text-transform:uppercase;letter-spacing:.05em">{{c.label}}</div><div style="font:800 22px 'JetBrains Mono';color:{{c.color}};margin:6px 0 2px">{{c.big}}</div><div style="font-size:11.5px;color:#6c7280">{{c.sub}} &rarr;</div></button></sc-for></div></div>
          </div>
          <div class="student-id-card"><input class="student-id-card__toggle" id="student-id-card-toggle" type="checkbox" aria-label="Flip student ID card" /><div class="student-id-card__frame"><div class="student-id-card__inner"><div class="student-id-card__face"><img src="/student-id/IDF.png" alt="Student ID card front" /></div><div class="student-id-card__face student-id-card__face--back"><img src="/student-id/IDB.png" alt="Student ID card back" /></div></div></div><div class="student-id-card__controls"><span class="student-id-card__caption">Student ID card</span><label class="student-id-card__flip" for="student-id-card-toggle" title="Flip student ID card"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 1l4 4-4 4"></path><path d="M3 11V9a4 4 0 0 1 4-4h14"></path><path d="M7 23l-4-4 4-4"></path><path d="M21 13v2a4 4 0 0 1-4 4H3"></path></svg><span class="student-id-card__flip-front">View back</span><span class="student-id-card__flip-back">View front</span></label></div></div>
        </div>
`;
  let html = source.replace('src="./support.js"', 'src="/design/runtime"');
  html = html.replace("duesTotal(){ const p=this.state.paid; return (p.hostel?0:42000)+(p.exam?0:1800); }", "duesTotal(){ const p=this.state.paid; return (p.hostel?0:42000)+(p.exam?0:1800)+20; }");
  html = html.replace("<div style=\"font-size:12px;color:#9096a4;font-weight:600;text-transform:uppercase;letter-spacing:.05em\">Total outstanding</div>", `${finesBreakdown}\n            <div style=\"font-size:12px;color:#9096a4;font-weight:600;text-transform:uppercase;letter-spacing:.05em\">Total outstanding</div>`);
  html = html.replace("<div style=\"font-size:12px;color:#6c7280;text-align:center\">Tuition & Transport cleared.<br/>Hostel & Exam fee pending.</div><div style=\"margin-top:14px\"><div style=\"display:flex;align-items:center;gap:8px;font-size:11.5px;color:#9096a4;font-weight:600;background:#f5f6fa;border:1px dashed rgba(25,20,60,.16);border-radius:9px;padding:9px 13px\"><svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#9096a4\" stroke-width=\"2\"><rect x=\"7\" y=\"2\" width=\"10\" height=\"20\" rx=\"2\"></rect><path d=\"M11 18h2\"></path></svg>Payments are made via the mobile app or campus counter.</div></div>", "");
  html = html.replace("        <sc-if value=\"{{payActive}}\" hint-placeholder-val=\"{{false}}\">", `${finesSection}        <sc-if value=\"{{payActive}}\" hint-placeholder-val=\"{{false}}\">`);

  const profileSectionRegex = /<sc-if value="\{\{show\.profile\}\}" hint-placeholder-val="\{\{false\}\}">[\s\S]*?<\/sc-if>/;
  html = html.replace(profileSectionRegex, `<sc-if value="{{show.profile}}" hint-placeholder-val="{{false}}">${profileStyles}${profileLayout}</sc-if>`);

  return new NextResponse(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
